var dir_7818f84a7a4f02d049158b157d2c5e42 =
[
    [ "ardour_button.h", "ardour__button_8h.html", "ardour__button_8h" ],
    [ "ardour_ctrl_base.h", "ardour__ctrl__base_8h.html", "ardour__ctrl__base_8h" ],
    [ "ardour_display.h", "ardour__display_8h.html", "ardour__display_8h" ],
    [ "ardour_dropdown.h", "ardour__dropdown_8h.html", "ardour__dropdown_8h" ],
    [ "ardour_fader.h", "ardour__fader_8h.html", "ardour__fader_8h" ],
    [ "ardour_icon.h", "ardour__icon_8h.html", "ardour__icon_8h" ],
    [ "ardour_knob.h", "ardour__knob_8h.html", "ardour__knob_8h" ],
    [ "ardour_spacer.h", "ardour__spacer_8h.html", "ardour__spacer_8h" ],
    [ "ardour_spinner.h", "ardour__spinner_8h.html", "ardour__spinner_8h" ],
    [ "barcontroller.h", "barcontroller_8h.html", "barcontroller_8h" ],
    [ "binding_proxy.h", "binding__proxy_8h.html", "binding__proxy_8h" ],
    [ "choice.h", "choice_8h.html", "choice_8h" ],
    [ "eventboxext.h", "eventboxext_8h.html", "eventboxext_8h" ],
    [ "fader_widget.h", "fader__widget_8h.html", "fader__widget_8h" ],
    [ "fastmeter.h", "fastmeter_8h.html", "fastmeter_8h" ],
    [ "focus_entry.h", "focus__entry_8h.html", "focus__entry_8h" ],
    [ "frame.h", "widgets_2widgets_2frame_8h.html", "widgets_2widgets_2frame_8h" ],
    [ "metabutton.h", "metabutton_8h.html", "metabutton_8h" ],
    [ "pane.h", "pane_8h.html", "pane_8h" ],
    [ "paths_dialog.h", "paths__dialog_8h.html", "paths__dialog_8h" ],
    [ "popup.h", "popup_8h.html", "popup_8h" ],
    [ "prompter.h", "prompter_8h.html", "prompter_8h" ],
    [ "scroomer.h", "scroomer_8h.html", "scroomer_8h" ],
    [ "searchbar.h", "searchbar_8h.html", "searchbar_8h" ],
    [ "slider_controller.h", "slider__controller_8h.html", "slider__controller_8h" ],
    [ "stateful_button.h", "stateful__button_8h.html", "stateful__button_8h" ],
    [ "tabbable.h", "tabbable_8h.html", "tabbable_8h" ],
    [ "tearoff.h", "tearoff_8h.html", "tearoff_8h" ],
    [ "tooltips.h", "widgets_2widgets_2tooltips_8h.html", "widgets_2widgets_2tooltips_8h" ],
    [ "ui_config.h", "libs_2widgets_2widgets_2ui__config_8h.html", "libs_2widgets_2widgets_2ui__config_8h" ],
    [ "visibility.h", "widgets_2widgets_2visibility_8h.html", "widgets_2widgets_2visibility_8h" ]
];