var dir_0347095a2216ed144caedc4488dad38f =
[
    [ "audio_engine_test.h", "audio__engine__test_8h.html", "audio__engine__test_8h" ],
    [ "audio_region_read_test.h", "audio__region__read__test_8h.html", "audio__region__read__test_8h" ],
    [ "audio_region_test.h", "audio__region__test_8h.html", "audio__region__test_8h" ],
    [ "automation_list_property_test.h", "automation__list__property__test_8h.html", "automation__list__property__test_8h" ],
    [ "bbt_test.h", "bbt__test_8h.html", "bbt__test_8h" ],
    [ "combine_regions_test.h", "combine__regions__test_8h.html", "combine__regions__test_8h" ],
    [ "control_surfaces_test.h", "control__surfaces__test_8h.html", "control__surfaces__test_8h" ],
    [ "dsp_load_calculator_test.h", "dsp__load__calculator__test_8h.html", "dsp__load__calculator__test_8h" ],
    [ "fpu_test.h", "fpu__test_8h.html", "fpu__test_8h" ],
    [ "load_sessions_test.h", "load__sessions__test_8h.html", "load__sessions__test_8h" ],
    [ "lua_script_test.h", "lua__script__test_8h.html", "lua__script__test_8h" ],
    [ "midi_clock_test.h", "midi__clock__test_8h.html", "midi__clock__test_8h" ],
    [ "mtdm_test.h", "mtdm__test_8h.html", "mtdm__test_8h" ],
    [ "playlist_equivalent_regions_test.h", "playlist__equivalent__regions__test_8h.html", "playlist__equivalent__regions__test_8h" ],
    [ "playlist_layering_test.h", "playlist__layering__test_8h.html", "playlist__layering__test_8h" ],
    [ "playlist_read_test.h", "playlist__read__test_8h.html", "playlist__read__test_8h" ],
    [ "plugins_test.h", "plugins__test_8h.html", "plugins__test_8h" ],
    [ "region_naming_test.h", "region__naming__test_8h.html", "region__naming__test_8h" ],
    [ "resampled_source_test.h", "resampled__source__test_8h.html", "resampled__source__test_8h" ],
    [ "samplepos_minus_beats_test.h", "samplepos__minus__beats__test_8h.html", "samplepos__minus__beats__test_8h" ],
    [ "samplepos_plus_beats_test.h", "samplepos__plus__beats__test_8h.html", "samplepos__plus__beats__test_8h" ],
    [ "samplewalk_to_beats_test.h", "samplewalk__to__beats__test_8h.html", "samplewalk__to__beats__test_8h" ],
    [ "session_test.h", "session__test_8h.html", "session__test_8h" ],
    [ "sha1_test.h", "sha1__test_8h.html", "sha1__test_8h" ],
    [ "tempo_test.h", "tempo__test_8h.html", "tempo__test_8h" ],
    [ "test_needing_session.h", "test__needing__session_8h.html", "test__needing__session_8h" ],
    [ "test_receiver.h", "test__receiver_8h.html", "test__receiver_8h" ],
    [ "test_ui.h", "test__ui_8h.html", "test__ui_8h" ],
    [ "test_util.h", "test__util_8h.html", "test__util_8h" ]
];